# -*- coding: utf-8 -*-
"""Aula03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uLItUqrD20eTwp4p8dpqHCdA14-T9Ty-
"""

print('Hello World!')

a = 2
b = 3

a != b

print (a != b)

a = 5
b = 10
c = 50

resultado = a*b == c

print(resultado)

#MAIOR
a = 100
b = 100

if(a>b):
  print('Caminho 1')
else:
   print('Caminho 2')

#MAIOR OU IGUAL
c = 100
d = 100

if(c>=d):
  print('Caminho 3')
else:
   print('Caminho 4')

numerador = int(input(prompt='Digite um numerador')
  if(input!=int):
print('Você não digitou um número inteiro')
  else:
denominador = int(input(prompt='Digite um denominador'))

print(int(numerador/denominador))

### 1 - Crie um programa para efetuar a leitura de um número inteiro e apresentar o resultado do quadrado deste número.
numero = int(input(prompt='Digite um numero'))
print('O número inserido (' + str(numero) + ') ao quadrado é: ' + str(numero*numero))

### 2 - Crie duas variáveis para armazenar seu primeiro nome e sobrenome. Em seguida, concatene-as para formar seu nome completo e exiba o resultado.
nome = input('Digite seu primeiro nome')
sobrenome = input('Digite seu sobrenome')
nome_completo = nome + ' ' + sobrenome
print(nome_completo)

### 3 - Peça ao usuário para digitar dois números inteiros e armazene-os em variáveis. Realize a concatenação desses números como strings e exiba o resultado.
numero1 = int(input('Digite o primeiro número:'))
numero2 = int(input('Digite o segundo número:'))
print(str(numero1) + str(numero2))

### 4 - Crie uma variável para armazenar a palavra "Python". Em seguida, adicione um número inteiro ao final da palavra usando a concatenação e exiba o resultado.
linguagem = 'Python'
numero = int(input('Digite um número:'))
print(linguagem + str(numero))

### 5 - Declare uma variável contendo uma frase. Em seguida, peça ao usuário para digitar uma palavra e concatene essa palavra no final da frase. Exiba o resultado.
frase = 'Qualquer coisa'
usuario = input('Digite uma frase:')
resultado = frase + usuario
print(resultado)

### 6 - Crie três variáveis para armazenar a quantidade de horas, minutos e segundos. Concatene esses valores para formar uma mensagem de tempo no formato "hh:mm:ss".
hora = input('Digite dois dígitos (de 0 a 23) referente a hora:')
minutos = input('Digite dois dígitos (de 0 a 59) referente aos minutos:')
segundos = input('Digite dois dígitos (de 0 a 59) referente a segundos:')
print('O horário (HH:MM:SS) informado foi: '+hora+':'+minutos+':'+segundos)

### 7 - Declare duas variáveis com números de telefone, incluindo um código de área e o número principal. Concatene esses valores para formar um número de telefone completo.
ddd = input('Digite o seu DDD com dois dígitos: ')
celular = input('Digite o seu número de celular com nove dígitos: ')
print('O celular informado foi :',ddd,celular)

### 8 - Crie uma lista de ingredientes para uma receita. Use concatenação para formar uma única string que liste os ingredientes separados por vírgulas.
##Bolo de cenoura
ingrediente1 = '3 cenouras médias'
ingrediente2 = '3 ovos'
ingrediente3 = '1 xícara de chá de óleo'
ingrediente4 = '2 xícaras de açúcar'
ingrediente5 = '2 xícaras de farinha de trigo'
ingrediente6 = '1 tampa de fermento'
print(ingrediente1,',',ingrediente2,',',ingrediente3,',',ingrediente4,',',ingrediente5,',',ingrediente6)

print('3 cenouras médias' + ',' + '3 ovos' + ',' + '1 xícara de chá de óleo' + ',' + '2 xícaras de açúcar' + ',' + '2 xícaras de farinha de trigo'+ ',' + '1 tampa de fermento')

### 9 - Peça ao usuário para digitar três adjetivos e armazene-os em variáveis. Em seguida, use essas palavras para criar uma frase concatenada que descreve algo interessante.
adjetivo1 = input('Digite o primeiro adjetivo: ')
adjetivo2 = inpforut('Digite o segundo adjetivo: ')
adjetivo3 = input('Digite o terceiro adjetivo: ')
print('Seu Madrugada disse ao Chaves que o homem tem que ser: ',adjetivo1,',',adjetivo2,'e',adjetivo3)